version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    ports:
      - "4004:8888"
    env_file:
      - ./backend/.env.production.local
    depends_on: 
      - db

  db:
    image: mongo:latest
    restart: always
    ports:
      - "27027:27017"
    env_file:
      - ./backend/.env.production.local
    volumes:
      - mongo_data:/data/db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  mongo_data:

networks:
  default:
    driver: bridge
    